---
title: "Untitled"
output: html_document
date: "2024-07-30"
---

```{r}
HNSC_fibroblast <- readRDS("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/HNSC_fibroblast.rds")
rownames(HNSC_fibroblast@meta.data) <- HNSC_fibroblast$Cell_Labels
file <- SplitObject(HNSC_fibroblast, split.by = "Chr_Dosage")
```

```{r}
#!/software/r/4.2.0/bin/Rscript
#BSUB -q long
#BSUB -W 10:00
#BSUB -n 4 
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=200GB]"
#BSUB -J Merge
#BSUB -u cristina.condelopez@dkfz-heidelberg.de

library(Seurat)
library(SeuratDisk)
library(SeuratWrappers)
library(UCell)
library(NMF)

HNSC_fibroblast <- readRDS("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/HNSC_fibroblast.rds")
rownames(HNSC_fibroblast@meta.data) <- HNSC_fibroblast$Cell_Labels
HNSC_fibroblast <- subset(HNSC_fibroblast, subset = HPV == "HPV-")
HNSC_fibroblast$Cells_Tumor_Integration[HNSC_fibroblast$Cells_Tumor_Integration == NA] <- c("Unknown")
HNSC_fibroblast <- SetIdent(HNSC_fibroblast, ident.use = "Cells_Fibroblast")
file <- SplitObject(HNSC_fibroblast, split.by = "Patient")


library(CellChat)

setwd("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient")
options(future.globals.maxSize = 8000 * 1024^2)
for (i in file){
 
meta <- i@meta.data
data.input <- GetAssayData(i, assay = "RNA", slot = "data")
cellchat <- createCellChat(object = data.input, meta = meta, group.by = "Cells_Tumor_Integration")
CellChatDB <- CellChatDB.human # use CellChatDB.mouse if running on mouse data
showDatabaseCategory(CellChatDB)
#CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling", key = "annotation") # use Secreted Signaling
# use all CellChatDB for cell-cell communication analysis
CellChatDB.use <- CellChatDB # simply use the default CellChatDB

# set the used database in the object
cellchat@DB <- CellChatDB.use
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
#future::plan("multisession", workers = 4) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)

# project gene expression data onto PPI (Optional: when running it, USER should set `raw.use = FALSE` in the function `computeCommunProb()` in order to use the projected data)
cellchat <- projectData(cellchat, PPI.human)
cellchat@idents = droplevels((cellchat@idents), exclude = setdiff(levels(cellchat@idents),unique(cellchat@idents)))

# 5. Compute the communication probability and infer cellular communication network
cellchat <- computeCommunProb(cellchat, raw.use = FALSE) 

# 6. Filter out the cell-cell communication min.cells = 10
cellchat <- filterCommunication(cellchat, min.cells = 10)

# 7. Infer the cell-cell communication at a signaling pathway level
cellchat <- computeCommunProbPathway(cellchat)

# 8. Calculate the aggregated cell-cell communication network
cellchat <- aggregateNet(cellchat)

# 9. Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")

# 10. Identify and visualize outgoing communication pattern of secreting cells
#selectK(cellchat, pattern = "outgoing") 
#nPatterns = 3
#cellchat <- identifyCommunicationPatterns(cellchat, pattern = "outgoing",
                                      #k = nPatterns, width = 5, height = 9)

# 11. Identify and visualize incoming communication pattern of target cells
#selectK(cellchat, pattern = "incoming")
#nPatterns = 3
#cellchat <- identifyCommunicationPatterns(cellchat,pattern = "incoming", 
                                      #k = nPatterns, width = 5, height = 9)

# 12. Identify signaling groups based on functional similarity
#cellchat <- computeNetSimilarity(cellchat, type = "functional")
#cellchat <- netEmbedding(cellchat, type = "functional")
#cellchat <- netClustering (cellchat, type = "functional", do.parallel = FALSE)

# 13. Identify signaling groups based on structure similarity
#cellchat <- computeNetSimilarity(cellchat, type = "structural")
#cellchat <- netEmbedding(cellchat, type = "structural")
#cellchat <- netClustering(cellchat, type = "structural", do.parallel = FALSE)

# 14. Save NL cellchat object
name <- paste0("HPVng_", unique(i$Patient), ".rds")
saveRDS(cellchat, file=name)
}

```

```{r}
library(CellChat)
library(tidyverse)

setwd("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient")
folder_path <- "/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient"

# List all files in the directory
files <- list.files(path = folder_path, pattern = "^HPVng_.*\\.rds$", full.names = TRUE) # Ensure it only lists .rds files

# Initialize an empty list to store cellchat objects
cellchats <- list()

for (i in files) {
  # Extract the base name without the extension for use as the list key
  name <- gsub("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient/HPVng_", "", i)
  name <- gsub(".rds", "", name)
  
  # Read the RDS file
  cellchat <- readRDS(i)
  setIdent(cellchat, ident.use = "Cells_Fibroblast")
  cellchat<- subsetCellChat(cellchat, idents.use = c("CD8T","Tumor","CD4T","Macrophage","Multi","NK","Monocyte","panDC","Neutrophils","Mast","Bcell","mCAF","tpCAF","Endothelial","PlasmaCell","Epithelial","IDO_CAF","iCAF","apCAF","Pericyte","rCAF+apCAF","vCAF","rCAF","Fibroblast","pericyte","dCAF"))
  
  # Store the cellchat object in the list under the derived name
  cellchats[[name]] <- cellchat
}
```


```{r}
#For XY patients

metadata <- HNSC_fibroblast@meta.data
XY <- subset(metadata, subset = Chr_Dosage == "XY")
XY <- subset(XY, subset = HPV == "HPV-")
XY_patient <- unique(XY$Patient)

XY_cellchats <- cellchats[names(cellchats) %in% XY_patient]

for (i in (1:length(XY_cellchats))){
  pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient/XY_heatmaps/", names(XY_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(XY_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(XY_cellchats[i]), "_XY"))
  dev.off()
}
```
 
```{r}
#For X0 patients

metadata <- HNSC_fibroblast@meta.data
X0 <- subset(metadata, subset = Chr_Dosage == "X0")
X0 <- subset(X0, subset = HPV == "HPV-")
X0_patient <- unique(X0$Patient)

X0_cellchats <- cellchats[names(cellchats) %in% X0_patient]

for (i in (1:length(X0_cellchats))){
  pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient/X0_heatmaps/", names(X0_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(X0_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(X0_cellchats[i]), "_X0"))
  dev.off()
}
```

```{r}
i = 10
 pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient/X0_heatmaps/", names(X0_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(X0_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(X0_cellchats[i]), "_X0"))
  dev.off()
```
```{r}
#For XX patients

metadata <- HNSC_fibroblast@meta.data
XX <- subset(metadata, subset = Chr_Dosage == "XX")
XX <- subset(XX, subset = HPV == "HPV-")
XX_patient <- unique(XX$Patient)

XX_cellchats <- cellchats[names(cellchats) %in% XX_patient]

for (i in (1:length(XX_cellchats))){
  pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient/XX_heatmaps/", names(XX_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(XX_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(XX_cellchats[i]), "_XX"))
  dev.off()
}
```

```{r}
i = 12
pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient/XX_heatmaps/", names(XX_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(XX_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(XX_cellchats[i]), "_XX"))
  dev.off()
```

```{r}
#!/software/r/4.2.0/bin/Rscript
#BSUB -q long
#BSUB -W 10:00
#BSUB -n 4 
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=200GB]"
#BSUB -J Merge
#BSUB -u cristina.condelopez@dkfz-heidelberg.de

library(Seurat)
library(SeuratDisk)
library(SeuratWrappers)
library(UCell)
library(NMF)

HNSC_fibroblast <- readRDS("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/HNSC_fibroblast.rds")
rownames(HNSC_fibroblast@meta.data) <- HNSC_fibroblast$Cell_Labels
HNSC_fibroblast <- subset(HNSC_fibroblast, subset = HPV == "HPV-")
HNSC_fibroblast$Cells_Tumor_Integration[HNSC_fibroblast$Cells_Tumor_Integration == NA] <- c("Unknown")
HNSC_fibroblast <- SetIdent(HNSC_fibroblast, ident.use = "Cells_Fibroblast")
file <- SplitObject(HNSC_fibroblast, split.by = "Patient")


library(CellChat)

setwd("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast")
options(future.globals.maxSize = 8000 * 1024^2)
for (i in file){
 
meta <- i@meta.data
data.input <- GetAssayData(i, assay = "RNA", slot = "data")
cellchat <- createCellChat(object = data.input, meta = meta, group.by = "Cells_Tumor_Integration")
CellChatDB <- CellChatDB.human # use CellChatDB.mouse if running on mouse data
showDatabaseCategory(CellChatDB)
#CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling", key = "annotation") # use Secreted Signaling
# use all CellChatDB for cell-cell communication analysis
CellChatDB.use <- CellChatDB # simply use the default CellChatDB

# set the used database in the object
cellchat@DB <- CellChatDB.use
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
#future::plan("multisession", workers = 4) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)

# project gene expression data onto PPI (Optional: when running it, USER should set `raw.use = FALSE` in the function `computeCommunProb()` in order to use the projected data)
cellchat <- projectData(cellchat, PPI.human)
cellchat@idents = droplevels((cellchat@idents), exclude = setdiff(levels(cellchat@idents),unique(cellchat@idents)))

# 5. Compute the communication probability and infer cellular communication network
cellchat <- computeCommunProb(cellchat, raw.use = FALSE) 

# 6. Filter out the cell-cell communication min.cells = 10
cellchat <- filterCommunication(cellchat, min.cells = 10)

# 7. Infer the cell-cell communication at a signaling pathway level
cellchat <- computeCommunProbPathway(cellchat)

# 8. Calculate the aggregated cell-cell communication network
cellchat <- aggregateNet(cellchat)

# 9. Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")

# 10. Identify and visualize outgoing communication pattern of secreting cells
#selectK(cellchat, pattern = "outgoing") 
#nPatterns = 3
#cellchat <- identifyCommunicationPatterns(cellchat, pattern = "outgoing",
                                      #k = nPatterns, width = 5, height = 9)

# 11. Identify and visualize incoming communication pattern of target cells
#selectK(cellchat, pattern = "incoming")
#nPatterns = 3
#cellchat <- identifyCommunicationPatterns(cellchat,pattern = "incoming", 
                                      #k = nPatterns, width = 5, height = 9)

# 12. Identify signaling groups based on functional similarity
#cellchat <- computeNetSimilarity(cellchat, type = "functional")
#cellchat <- netEmbedding(cellchat, type = "functional")
#cellchat <- netClustering (cellchat, type = "functional", do.parallel = FALSE)

# 13. Identify signaling groups based on structure similarity
#cellchat <- computeNetSimilarity(cellchat, type = "structural")
#cellchat <- netEmbedding(cellchat, type = "structural")
#cellchat <- netClustering(cellchat, type = "structural", do.parallel = FALSE)

# 14. Save NL cellchat object
name <- paste0("HPVng_", unique(i$Patient), ".rds")
saveRDS(cellchat, file=name)
}

```

```{r}
library(CellChat)
library(tidyverse)

setwd("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast")
folder_path <- "/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast"

# List all files in the directory
files <- list.files(path = folder_path, pattern = "^HPVng_.*\\.rds$", full.names = TRUE) # Ensure it only lists .rds files

# Initialize an empty list to store cellchat objects
cellchats <- list()

for (i in files) {
  # Extract the base name without the extension for use as the list key
  name <- gsub("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast/HPVng_", "", i)
  name <- gsub(".rds", "", name)
  
  # Read the RDS file
  cellchat <- readRDS(i)
  cellchat<- subsetCellChat(cellchat, idents.use = c("CD8T","Tumor","CD4T","Macrophage","Multi","NK","Monocyte","panDC","Neutrophils","Mast","Bcell","mCAF","tpCAF","Endothelial","PlasmaCell","Epithelial","IDO_CAF","iCAF","apCAF","Pericyte","rCAF+apCAF","vCAF","rCAF","Fibroblast","pericyte","dCAF"))
  
  # Store the cellchat object in the list under the derived name
  cellchats[[name]] <- cellchat
}
```

```{r}
#For XY patients
HNSC_fibroblast <- readRDS("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/HNSC_fibroblast.rds")
metadata <- HNSC_fibroblast@meta.data
XY <- subset(metadata, subset = Chr_Dosage == "XY")
XY <- subset(XY, subset = HPV == "HPV-")
XY_patient <- unique(XY$Patient)

XY_cellchats <- cellchats[names(cellchats) %in% XY_patient]

for (i in (1:length(XY_cellchats))){
  pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast/XY_heatmaps/", names(XY_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(XY_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(XY_cellchats[i]), "_XY"))
  dev.off()
}
```
```{r}
i = 1
pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast/XY_heatmaps/", names(XY_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(XY_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(XY_cellchats[i]), "_XY"))
  dev.off()
```

```{r}
# Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
# Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups
netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 8, height = 2.5, font.size = 10)
# Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
ht1 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing")
```

```{r}
#For X0 patients

metadata <- HNSC_fibroblast@meta.data
X0 <- subset(metadata, subset = Chr_Dosage == "X0")
X0 <- subset(X0, subset = HPV == "HPV-")
X0_patient <- unique(X0$Patient)

X0_cellchats <- cellchats[names(cellchats) %in% X0_patient]

for (i in (1:length(X0_cellchats))){
  pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast/X0_heatmaps/", names(X0_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(X0_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(X0_cellchats[i]), "_X0"))
  dev.off()
}
```

```{r}
i = 10
  pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast/X0_heatmaps/", names(X0_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(X0_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(X0_cellchats[i]), "_X0"))
  dev.off()
```


```{r}
i = 10
 pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient/X0_heatmaps/", names(X0_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(X0_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(X0_cellchats[i]), "_X0"))
  dev.off()
```
```{r}
#For XX patients

metadata <- HNSC_fibroblast@meta.data
XX <- subset(metadata, subset = Chr_Dosage == "XX")
XX <- subset(XX, subset = HPV == "HPV-")
XX_patient <- unique(XX$Patient)

XX_cellchats <- cellchats[names(cellchats) %in% XX_patient]

for (i in (1:length(XX_cellchats))){
  pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient/XX_heatmaps/", names(XX_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(XX_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(XX_cellchats[i]), "_XX"))
  dev.off()
}
```

```{r}
i = 15
pdf(file= paste0("/omics/odcf/analysis/OE0509_projects/hnscc/single_cell/Single_Cell_Analysis/Single_Cell_Datasets/All_Cells_Together/Integration/Cell_Chat_Patient_Fibroblast/XX_heatmaps/", names(XX_cellchats[i]), ".pdf"), width = 12, height = 6)
  netVisual_heatmap(XX_cellchats[[i]], measure = "weight", signaling = NULL, color.heatmap = "Reds", title.name = paste0(names(XX_cellchats[i]), "_XX"))
  dev.off()
```
```{r}
cellchats[[1]] <- netAnalysis_computeCentrality(cellchats[[1]], slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
# Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups
netAnalysis_signalingRole_network(cellchats[[1]], width = 8, height = 2.5, font.size = 10)
# Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
netAnalysis_signalingRole_heatmap(cellchats[[1]], pattern = "outgoing")
```

