---
title: "HIPO_GSVA"
author: "Cristina Conde Lopez"
date: "5/4/2022"
output: html_document
---
```{r}
library(GEOquery)
```


```{r}
gse=getGEO(filename="./GSE117973_series_matrix.txt.gz")
```

```{r}
str(phenoData(gse)@data)
```

```{r}
phenoData(gse)@data$`Sex:ch1`
```
```{r}
View(phenoData(gse)@data)
```

```{r}
exprs <- na.omit(as.data.frame(assayData(gse)$exprs))
```

```{r}
ids <- rownames(exprs)
```


```{r}
mytargets <- phenoData(gse)@data[,c(1,2,56)]
colnames(mytargets) <- c("title", "geo_accession", "Sex" )
```

```{r}
library(illuminaHumanv4.db)
```

```{r}
x <- illuminaHumanv4GENENAME(rownames(exprs))
```
```{r}
x <- as.data.frame(ls(illuminaHumanv4GENENAME))
```

```{r}
syms <- as.data.frame(na.omit(unlist(mget(ids, illuminaHumanv4ENSEMBL))))
```
```{r}
colnames(syms) <- c("ENSMBL")
```


```{r}
i <- which(  rownames(syms) %in% rownames(exprs))
```

```{r}
syms1 <- syms[i,]
```

```{r}
i <- which(rownames(exprs) %in% rownames(syms))
```
```{r}
exprs1 <- exprs[i,]
```

```{r}
exprs1$ENSMBL <- syms1
```

```{r}
library("org.Hs.eg.db") # remember to install it if you don't have it already
symbols <- mapIds(org.Hs.eg.db, keys = exprs1$ENSMBL, keytype = "ENSEMBL", column="SYMBOL")
```

```{r}
exprs1$SYMBOL <- symbols
```

```{r}

```


```{r}
rownames(exprs1) <- exprs1$SYMBOL
```


```{r}
library(GSVA)
library(GSEABase)
library(GSVAdata)
```
```{r}
genes <- geneIds(GeneSetCollection[[1]])
```

```{r}
exprsy <- exprs1[i,]
```

```{r}
exprs2 <- exprs1[,-78]
```

```{r}
i <- which(exprs1$SYMBOL %in%  genes)
```

```{r}
med <- aggregate(. ~ SYMBOL, data = exprsy, FUN = max)
```

```{r}
A <- aggregate(. ~ SYMBOL, data = exprs2, FUN = mean,
          na.rm = TRUE)
```

```{r}
rownames(A) <- A$SYMBOL
```

```{r}
A1 <- A[,-1]
```



```{r}

```


```{r}
rownames(med) <- med$SYMBOL
```
```{r}
med <- med[,c(-1,-79)]
```

```{r}
medmax <- as.matrix(sapply(med, as.numeric))

```

```{r}
rownames(medmax) <- rownames(med)
```


```{r}
GeneSetCollection <- getGmt("genesignature_Y_chromosome.gmt")
```

```{r}
GSVA_HIPO <- gsva((as.matrix(A1)), GeneSetCollection, method = "gsva", annotation = "org.Hs.eg.db", min.sz=5, max.sz=500, parallel.sz = 4, kcdf="Gaussian")
```
```{r}
mytargets$GSVA_Y_score <- GSVA_HIPO[1,]
```

```{r}
geneIds(GeneSetCollection)
```


```{r}
library(pheatmap)
  choose_matrix=GSVA_HIPO
  #clustering2 <- hclust(dist(t(choose_matrix), method = "euclidean"), method = "ward.D2")
  ## http://www.bio-info-trainee.com/1980.html
  annotation_col = data.frame(Gender = mytargets$Sex, EDY = mytargets$EDY)
  rownames(annotation_col)=colnames(GSVA_HIPO)
  pheatmap(choose_matrix,show_colnames = F,annotation_col = annotation_col, 
           #cluster_cols = clustering2, cutree_cols = 3,
           #filename = "GSVA_HIPO.png",
           cluster_rows = F)
```

```{r}
library(ggplot2)
```

```{r}
ggplot(mytargets, aes(x=Sex, y=GSVA_Y_score, fill=Sex)) +
  xlab("Gender") +
  ylab("GSVA score") +
  geom_violin(trim=F) +
  geom_boxplot(width=0.1) +
  #stat_compare_means(label.y = 1.3) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
```
```{r}
female <- mytargets[mytargets$Sex == "female",]
```

```{r}
max(female$GSVA_Y_score)
```

```{r}
male <- mytargets[mytargets$Sex == "male",]
```

```{r}
x1<-rep(c(0),times=nrow(male))
```

```{r}
for (i in c(1:60)){
  if(male$GSVA_Y_score[i] < -0.2799177){
    x1[i] <- c("Yes")
    } else {
      x1[i] <- c("No")
    }
}
```

```{r}
x1 
```

```{r}
fem <-rep(c("female"),times=nrow(mytargets))
```

```{r}
i <- which(mytargets$title  %in% male$title)
```

```{r}
fem[i] <- x1
```

```{r}
fem
```


```{r}
mytargets$EDY <- fem
```

```{r}
write.csv(mytargets, file = "/Users/cristinacondel/Desktop/HIPO/HIPO_EDY.cvs")
```

```{r}
which(celllines_counts$Description == "PTGS2")
```

```{r}
ptgs2 <- celllines_counts[4075,]
```

```{r}
ptgs2 <- ptgs2[,c(-1,-2)]
```

```{r}
names <- gsub("\\_.*","",colnames(ptgs2))
```

```{r}
colnames(ptgs2) <- names
```

```{r}
i <- which( colnames(ptgs2) %in% LoY_cell_info$Cell_Lines)
```

```{r}
ptgs2hn <- ptgs2[,i]
```

```{r}
colnames(ptgs2hn)
LoY$Cell_Lines
```

```{r}
LoY$PGST2 <- as.numeric(c(ptgs2hn[1,]))
```

```{r}
my_comparisons <- list( c("No", "Yes"))
```

```{r}
ggplot(LoY, aes(x=LoY, y=log2(PGST2 + 1), fill=LoY)) +
  xlab("LoY") +
  ylab("Expression level: Log2(x+1)") +
  geom_violin(trim=F) +
  geom_boxplot(width=0.1) +
  stat_compare_means(comparisons = my_comparisons
                     , label.y = c(20)
                     ) +
  #stat_compare_means(label.y = 1.3) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
```
```{r}
which(celllines_counts$Description == "IL1B")
```

```{r}
ptgs2 <- celllines_counts[7240,]
```

```{r}
ptgs2 <- ptgs2[,c(-1,-2)]
```

```{r}
names <- gsub("\\_.*","",colnames(ptgs2))
```

```{r}
colnames(ptgs2) <- names
```

```{r}
i <- which( colnames(ptgs2) %in% LoY_cell_info$Cell_Lines)
```

```{r}
i <- which(LoY_cell_info$Cell_Lines  %in%  colnames(ptgs2hn))
```

```{r}
LoY <- LoY_cell_info[i,]
```

```{r}
ptgs2hn <- ptgs2[,i]
```

```{r}
#Se puede hacer primero para comprobar si ya de base son iguales
colnames(gmtfile_deacuerdoconclinicaldata) == rownames(clicaldata)
#Si no lo son puedes buscar que columnas están dentro del clinical data
i <- which(colnames(gmtfile) %in% rownames(clicaldata))
#Se puede comprobar también en la otra dirección clinical data dentro de counts
j <- which(rownames(clicaldata)  %in%  colnames(gmtfile))
#Extraemos los matches y creamos nuevos datasets
gmtfile_deacuerdoconclinicaldata <- gmtfile[,i]
clinicaldata_deacuercongmtfileclicaldata[,j]
#Comprobamos de nuevo que todo esta de acuerdo
colnames(gmtfile_deacuerdoconclinicaldata) == rownames(clicaldata)
#Una vez esta de acuerdo creas una nueva variable en tu clinicaldata que sea tu valor score
clinicaldata_deacuercongmtfileclicaldata$GSVA_score <- as.numeric(c(gmtfile_deacuerdoconclinicaldata[1,]))
```

```{r}
colnames(ptgs2hn)
LoY$Cell_Lines
```

```{r}
LoY$IL1B <- as.numeric(c(ptgs2hn[1,]))
```

```{r}
my_comparisons <- list( c("No", "Yes"))
```

```{r}
ggplot(LoY, aes(x=LoY, y=log2(IL1B + 1), fill=LoY)) +
  xlab("LoY") +
  ylab("Expression level: Log2(x+1)") +
  geom_violin(trim=F) +
  geom_boxplot(width=0.1) +
  stat_compare_means(comparisons = my_comparisons
                     , label.y = c(20)
                     ) +
  #stat_compare_means(label.y = 1.3) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

```{r}
rownames(celllines_counts) <- celllines_counts$Name
```

```{r}
counts <- celllines_counts[,c(-1,-2)]
```

```{r}
celllines <- sample_info[sample_info$primary_disease =="Head and Neck Cancer",]
```

```{r}
which(TCGA_TPM_symbol$A == "PTGS2")
```

```{r}
ptg <- TCGA_TPM_symbol[21531,]
```

```{r}
ptg <- ptg[,-1]
```

```{r}
TCGA_EDY_LOY$PTGS2 <- c(ptg)
```

```{r}
library(ggplot2)
library(ggpubr)
```


```{r}
my_comparisons <- list( c("female", "No", "Yes"))
```

```{r}
ggplot(TCGA_EDY_LOY, aes(x=LoY, y=log2(as.numeric(PTGS2) + 1), fill=LoY)) +
  xlab("LoY") +
  ylab("Expression level: Log2(x+1)") +
  geom_violin(trim=F) +
  geom_boxplot(width=0.1) +
  #stat_compare_means(label.y = 1.3) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

```{r}
which(rownames(TCGA_TPM_symbol) == "IL1B")
```

```{r}
ptg <- TCGA_TPM_symbol[9799,]
```

```{r}
ptg <- ptg[,-1]
```

```{r}
TCGA_EDY_LOY$IL1B <- c(ptg)
```

```{r}
library(ggplot2)
library(ggpubr)
```


```{r}
my_comparisons <- list( c("female", "No", "Yes"))
```

```{r}
ggplot(TCGA_EDY_LOY, aes(x=LoY, y=log2(as.numeric(IL1B) + 1), fill=LoY)) +
  xlab("LoY") +
  ylab("Expression level: Log2(x+1)") +
  geom_violin(trim=F) +
  geom_boxplot(width=0.1) +
  #stat_compare_means(label.y = 1.3) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
```
